<?php
declare(strict_types=1);

// Single source of truth for every tool on iLoveMyFile.
//
// Add a new tool by adding ONE entry here (slug => details) and adding its
// markup/view block in index.php. Do not duplicate this list anywhere else —
// sitemap.php reads directly from this file, so any tool added here appears
// in the sitemap automatically on the next crawl. No separate sitemap edit
// is ever needed.
//
// 'lastmod' should be updated (YYYY-MM-DD) whenever a tool's page content or
// functionality meaningfully changes, so search engines know to re-crawl it.
$tools = [
    'merge-pdf' => [
        'name' => 'Merge PDF',
        'category' => 'PDF Tools',
        'description' => 'Combine multiple PDF files into one PDF online for free.',
        'seo_title' => 'Merge PDF – Free Online PDF Merger | iLoveMyFile',
        'seo_description' => 'Merge multiple PDF files into one document online for free. Fast, simple and privacy-conscious PDF merging with iLoveMyFile.',
        'keywords' => 'merge pdf, pdf merger, combine pdf, join pdf files, merge pdf online',
        'view' => 'merge-pdf',
        'lastmod' => '2026-09-01',
    ],
    'compress-image' => [
        'name' => 'Compress Image to Target Size',
        'category' => 'Image Tools',
        'description' => 'Compress JPG, PNG and WebP images toward a target file size such as 50 KB, 100 KB, 200 KB or a custom size.',
        'seo_title' => 'Compress Image to 50KB, 100KB, 200KB & More – Free Online Image Compressor | iLoveMyFile',
        'seo_description' => 'Compress images to 50KB, 100KB, 200KB, 300KB, 500KB or a custom target size. Choose an output format and download the optimized image in your browser.',
        'keywords' => 'compress image to 50kb, compress image to 100kb, compress image to 200kb, compress image to 300kb, compress image to 500kb, image compressor, reduce image size, compress jpg',
        'view' => 'compress-image',
        'lastmod' => '2026-09-01',
    ],
    'split-pdf' => [
        'name' => 'Split PDF',
        'category' => 'PDF Tools',
        'description' => 'Split a PDF by page range, or into odd, even or individual pages. Download as separate PDFs or one combined file.',
        'seo_title' => 'Split PDF – Extract or Divide PDF Pages Online Free | iLoveMyFile',
        'seo_description' => 'Split a PDF into separate files or extract specific pages by range. Choose all pages, odd pages, even pages or a custom range, free and in your browser.',
        'keywords' => 'split pdf, split pdf online, extract pdf pages, divide pdf, pdf splitter, split pdf into pages, extract pages from pdf',
        'view' => 'split-pdf',
        'lastmod' => '2026-09-01',
    ],
    'compress-pdf' => [
        'name' => 'Compress PDF',
        'category' => 'PDF Tools',
        'description' => 'Reduce PDF file size by optimizing structure, removing unused objects and stripping unnecessary metadata.',
        'seo_title' => 'Compress PDF – Reduce PDF File Size Online Free | iLoveMyFile',
        'seo_description' => 'Compress a PDF online for free by optimizing its internal structure and removing unnecessary metadata. Fast, private and browser-based.',
        'keywords' => 'compress pdf, reduce pdf size, pdf compressor, shrink pdf, make pdf smaller, optimize pdf',
        'view' => 'compress-pdf',
        'lastmod' => '2026-09-02',
    ],
    'jpg-to-pdf' => [
        'name' => 'JPG to PDF',
        'category' => 'PDF Tools',
        'description' => 'Convert one or more JPG images into a single PDF file online for free.',
        'seo_title' => 'JPG to PDF – Convert JPG Images to PDF Online Free | iLoveMyFile',
        'seo_description' => 'Convert JPG images to a PDF file for free. Add multiple photos, reorder them, and download one combined PDF. Fast, private and browser-based.',
        'keywords' => 'jpg to pdf, convert jpg to pdf, jpeg to pdf, image to pdf converter, jpg to pdf online',
        'view' => 'image-to-pdf',
        'accept' => 'image/jpeg',
        'lastmod' => '2026-09-03',
    ],
    'png-to-pdf' => [
        'name' => 'PNG to PDF',
        'category' => 'PDF Tools',
        'description' => 'Convert one or more PNG images into a single PDF file online for free.',
        'seo_title' => 'PNG to PDF – Convert PNG Images to PDF Online Free | iLoveMyFile',
        'seo_description' => 'Convert PNG images to a PDF file for free. Add multiple images, reorder them, and download one combined PDF. Fast, private and browser-based.',
        'keywords' => 'png to pdf, convert png to pdf, png to pdf online, image to pdf converter',
        'view' => 'image-to-pdf',
        'accept' => 'image/png',
        'lastmod' => '2026-09-03',
    ],
    'image-to-pdf' => [
        'name' => 'Image to PDF',
        'category' => 'PDF Tools',
        'description' => 'Convert JPG, PNG and WebP images into a single PDF file online for free.',
        'seo_title' => 'Image to PDF – Convert JPG, PNG & WebP to PDF Online Free | iLoveMyFile',
        'seo_description' => 'Convert JPG, PNG or WebP images to a PDF file for free. Add multiple images, reorder them, and download one combined PDF. Fast, private and browser-based.',
        'keywords' => 'image to pdf, convert image to pdf, photo to pdf, picture to pdf, jpg png to pdf',
        'view' => 'image-to-pdf',
        'accept' => 'image/jpeg,image/png,image/webp',
        'lastmod' => '2026-09-03',
    ],
    'pdf-to-jpg' => [
        'name' => 'PDF to JPG',
        'category' => 'PDF Tools',
        'description' => 'Convert every page of a PDF into a JPG image online for free.',
        'seo_title' => 'PDF to JPG – Convert PDF Pages to JPG Images Online Free | iLoveMyFile',
        'seo_description' => 'Convert a PDF to JPG images for free. Every page becomes its own JPG, delivered as a ZIP. Fast, private and browser-based.',
        'keywords' => 'pdf to jpg, convert pdf to jpg, pdf to image, pdf to jpeg, pdf to jpg online, pdf page to image',
        'view' => 'pdf-to-jpg',
        'lastmod' => '2026-09-04',
    ],
    'rotate-pdf' => [
        'name' => 'Rotate PDF',
        'category' => 'PDF Tools',
        'description' => 'Rotate every page of a PDF 90, 180 or 270 degrees online for free.',
        'seo_title' => 'Rotate PDF – Rotate PDF Pages Online Free | iLoveMyFile',
        'seo_description' => 'Rotate a PDF online for free. Fix sideways or upside-down scans by rotating every page 90, 180 or 270 degrees. Fast, private and browser-based.',
        'keywords' => 'rotate pdf, rotate pdf pages, rotate pdf online, fix sideways pdf, rotate pdf 90 degrees',
        'view' => 'rotate-pdf',
        'lastmod' => '2026-09-05',
    ],
    'jpg-to-webp' => [
        'name' => 'JPG to WebP',
        'category' => 'Image Tools',
        'description' => 'Convert JPG images to WebP online for free, for smaller files and faster websites.',
        'seo_title' => 'JPG to WebP – Convert JPG to WebP Online Free | iLoveMyFile',
        'seo_description' => 'Convert JPG images to WebP for free. Smaller files, faster pages. Fast, private and browser-based.',
        'keywords' => 'jpg to webp, convert jpg to webp, jpeg to webp, jpg to webp online, jpg to webp converter',
        'view' => 'image-convert',
        'from' => 'image/jpeg',
        'to' => 'image/webp',
        'accept' => 'image/jpeg',
        'lastmod' => '2026-09-06',
    ],
    'png-to-webp' => [
        'name' => 'PNG to WebP',
        'category' => 'Image Tools',
        'description' => 'Convert PNG images to WebP online for free, for smaller files and faster websites.',
        'seo_title' => 'PNG to WebP – Convert PNG to WebP Online Free | iLoveMyFile',
        'seo_description' => 'Convert PNG images to WebP for free. Smaller files, faster pages, transparency preserved. Fast, private and browser-based.',
        'keywords' => 'png to webp, convert png to webp, png to webp online, png to webp converter',
        'view' => 'image-convert',
        'from' => 'image/png',
        'to' => 'image/webp',
        'accept' => 'image/png',
        'lastmod' => '2026-09-06',
    ],
    'webp-to-jpg' => [
        'name' => 'WebP to JPG',
        'category' => 'Image Tools',
        'description' => 'Convert WebP images to JPG online for free.',
        'seo_title' => 'WebP to JPG – Convert WebP to JPG Online Free | iLoveMyFile',
        'seo_description' => 'Convert WebP images to JPG for free, for compatibility with apps and sites that need JPG. Fast, private and browser-based.',
        'keywords' => 'webp to jpg, convert webp to jpg, webp to jpeg, webp to jpg online, webp to jpg converter',
        'view' => 'image-convert',
        'from' => 'image/webp',
        'to' => 'image/jpeg',
        'accept' => 'image/webp',
        'lastmod' => '2026-09-06',
    ],
    'webp-to-png' => [
        'name' => 'WebP to PNG',
        'category' => 'Image Tools',
        'description' => 'Convert WebP images to PNG online for free.',
        'seo_title' => 'WebP to PNG – Convert WebP to PNG Online Free | iLoveMyFile',
        'seo_description' => 'Convert WebP images to PNG for free, preserving transparency. Fast, private and browser-based.',
        'keywords' => 'webp to png, convert webp to png, webp to png online, webp to png converter',
        'view' => 'image-convert',
        'from' => 'image/webp',
        'to' => 'image/png',
        'accept' => 'image/webp',
        'lastmod' => '2026-09-06',
    ],
    'resize-image' => [
        'name' => 'Resize Image',
        'category' => 'Image Tools',
        'description' => 'Resize JPG, PNG and WebP images to exact dimensions, a percentage, or a common preset size, online for free.',
        'seo_title' => 'Resize Image – Resize JPG, PNG & WebP Online Free | iLoveMyFile',
        'seo_description' => 'Resize an image to exact dimensions, a percentage scale, or a common preset like 1080x1080. Fast, private and browser-based.',
        'keywords' => 'resize image, resize image online, resize picture, image resizer, resize photo, resize image to pixels',
        'view' => 'resize-image',
        'lastmod' => '2026-09-07',
    ],
    'add-page-numbers' => [
        'name' => 'Add Page Numbers',
        'category' => 'PDF Tools',
        'description' => 'Add page numbers to a PDF online for free, with a choice of position and starting number.',
        'seo_title' => 'Add Page Numbers to PDF – Free Online Tool | iLoveMyFile',
        'seo_description' => 'Add page numbers to a PDF for free. Choose the position and starting number. Fast, private and browser-based.',
        'keywords' => 'add page numbers to pdf, pdf page numbers, number pdf pages, insert page numbers pdf, pdf page numbering online',
        'view' => 'add-page-numbers',
        'lastmod' => '2026-09-08',
    ],
    'remove-pdf-pages' => [
        'name' => 'Remove PDF Pages',
        'category' => 'PDF Tools',
        'description' => 'Delete specific pages from a PDF online for free.',
        'seo_title' => 'Remove PDF Pages – Delete Pages From a PDF Online Free | iLoveMyFile',
        'seo_description' => 'Delete specific pages from a PDF for free. Enter the pages or ranges to remove and download the rest. Fast, private and browser-based.',
        'keywords' => 'remove pdf pages, delete pdf pages, remove pages from pdf, delete pages from pdf online, pdf page remover',
        'view' => 'remove-pdf-pages',
        'lastmod' => '2026-09-09',
    ],
    'extract-pdf-pages' => [
        'name' => 'Extract PDF Pages',
        'category' => 'PDF Tools',
        'description' => 'Pull specific pages out of a PDF into a new file, online for free.',
        'seo_title' => 'Extract PDF Pages – Pull Pages From a PDF Online Free | iLoveMyFile',
        'seo_description' => 'Extract specific pages from a PDF into a new file for free. Enter the pages or ranges to keep. Fast, private and browser-based.',
        'keywords' => 'extract pdf pages, extract pages from pdf, pull pages from pdf, pdf page extractor, get pages from pdf online',
        'view' => 'extract-pdf-pages',
        'lastmod' => '2026-09-10',
    ],
    'json-formatter' => [
        'name' => 'JSON Formatter',
        'category' => 'Developer Tools',
        'description' => 'Format, validate and beautify JSON online for free, with clear error messages for invalid JSON.',
        'seo_title' => 'JSON Formatter – Format & Validate JSON Online Free | iLoveMyFile',
        'seo_description' => 'Format and validate JSON online for free. Paste or upload JSON, beautify it with proper indentation, and get clear errors if it\u2019s invalid. Fast and browser-based.',
        'keywords' => 'json formatter, json validator, json beautifier, format json online, pretty print json, validate json',
        'view' => 'json-formatter',
        'lastmod' => '2026-09-11',
    ],
];
